src/pugixml.cpp
tests/test_parse.cpp

added some tests to force invalid buffer and size = 0

load_buffer_impl always checks if buffer is valid pointer and size > 0

---

src/pugixml.cpp

Fixed a linking issue of multiple definitions in header only mode.

Fixed missing PUGI__FN

---

LICENSE
scripts/pugixml.podspec
scripts/push_to_cocoapods.sh

This is the PR to fix https://github.com/zeux/pugixml/issues/84

add cocoapods package

---

scripts/pugixml_vs2013.vcxproj
scripts/pugixml_vs2013_static.vcxproj

Hello, zeux, vs2013 projects files may be useful for users with 2013 studio only

Add vs2013 projects

---

src/pugixml.cpp

Integer sanitizer is flagging unsigned integer overflow in several
functions in pugixml; unsigned integer overflow is well defined but it
may not necessarily be intended.
Apart from hash functions, both string_to_integer and integer_to_string
use unsigned overflow - string_to_integer uses it to perform
two-complement negation so that the bulk of the operation can run using
unsigned integers. This makes it possible to simplify overflow checking.
Similarly integer_to_string negates the number before generating a
decimal representation, but negating is impossible without unsigned
overflow or special-casing certain integer limits.
For now just silence the integer overflow using a special attribute;
also move unsigned overflow into string_to_integer from get_value_* so
that we have fewer …

Work around -fsanitize=integer issues

---

appveyor.yml
scripts/nuget_build.ps1
tests/autotest-appveyor.ps1

Also cleanup nuget_build.ps1 a bit.

Add VS2017 to AppVeyour test run

---

docs/manual.adoc
src/pugixml.cpp
src/pugixml.hpp
tests/test_control_chars.cpp

format_skip_control_chars

---

tests/test_xpath.cpp

use <random> 's generator and std::shuffle instead

std::random_shuffle is removed in current standard

---

docs/manual.adoc
docs/manual.html
src/pugixml.cpp
src/pugixml.hpp
tests/test_write.cpp

closes https://github.com/zeux/pugixml/issues/274

Feature single quote support

---

tests/test_parse_doctype.cpp
tests/test_xpath_operators.cpp

- Typos were found by codespell v1.15.0

Fix minor typos

---

docs/manual.adoc
src/pugixml.cpp
src/pugixml.hpp
tests/test_dom_modify.cpp

feat: add remove_attributes() and remove_children()

---

appveyor.yml

PS invocation of code coverage upload gets triggered because of stderr
output from curl with progress report when uploading coverage.

Fix PowerShell errors on stderr

---

CMakeLists.txt

[Cmake] Static build should not export APIs

---

docs/manual.adoc
scripts/pugixml-config.cmake.in

---
This change came as news to us. Adding a release note and compatibility for others in the future :) .

Update 1.11 release notes

---

appveyor.yml
scripts/nuget/pugixml.nuspec
scripts/nuget_build.ps1
scripts/pugixml_vs2022.vcxproj
scripts/pugixml_vs2022_static.vcxproj
tests/autotest-appveyor.ps1

Hi Arseny,
I would like to use pugixml within a project developed in VS 2022 with platform toolset v143. Please have a look at my pull request and if it is working as expected I am happy when you accept it and update the official Nuget package sources.
Cheers Tobias

Add support for Visual Studio 2022 with Platform Toolset v143.

---

tests/test_xpath.cpp

Instead of trying to detect if we can safely use random shuffle simply reimplement it ourselves.
The quality of the RNG is not essential for these tests.
Fixes #481

tests: Fix MSVC 2022 build

---

src/pugixml.cpp

Fix memory leak

---

src/pugixml.cpp
src/pugixml.hpp
tests/test_dom_modify.cpp
tests/test_dom_text.cpp

Fixes comments in https://github.com/zeux/pugixml/pull/490

Followup on pr 490

---

src/pugixml.cpp
src/pugixml.hpp

Useful when creating values from std::string_view

Added bool set_value(const char_t* rhs, size_t sz).

---

CMakeLists.txt
scripts/pugixml.pc.in

Resolves https://github.com/zeux/pugixml/issues/536

Relative and absolute paths for a relocatable pkgconf file
