zeux/pugixml

- src/pugixml.cpp
- src/pugixml.hpp
- tests/test_dom_modify.cpp
The issue: Double values are printed with insufficient precision #18 
Has a link to a site that offers a solution.  This patch implements that solution.
I tested the solution for floats by iterating through all values between:
std::numeric_limits<float>::min() and std::numeric_limits<float>::max(), converting to a string, then parsing the string and I obtained the value I started with.
On my machine the test for float took about 20 minutes to run on 8 cores.
I didn't attempt to run the same test with a double since I think it would take too long to run the test.
> Add xml_text::set for float, make float/double round-trip

- src/pugixml.cpp
- src/pugixml.hpp
- tests/test_write.cpp
Hi!
Here is PR with support for alignment each attribute on next line.
This alignment can simplify merge two files scenarios (for example, for compare two revisions of configuration files if only one of multiple attributes was changed).
Added `format_indent_attribute` mode:
```xml
<node
attr="1"
other="2">
</node>
<node
attr="1"
other="2" />
```
Added `format_indent_full` mode:
```xml
<node
attr="1"
other="2"
>
<sub />
</node>
<node
attr="1"
other="2"
/>
```
Would you like to accept this PR?
Thanks for great library!
Best regards, Aleksei.
> Align attributes each on separate line

- docs/manual.adoc
- src/pugixml.cpp
- src/pugixml.hpp
- tests/test_parse.cpp
This flag determines if plain character data is be stored in the parent element's value. This significantly changes the structure of the document and does not allow some documents to round-trip; this flag is only recommended for parsing documents with a lot of PCDATA nodes in a very memory-constrained environment.
Note: this PR is incomplete (missing tests and documentation)
> Add parse_embed_pcdata flag

- src/pugixml.cpp
Do not assume that fclose can be converted to int(* )(FILE*) because some compilers use a special calling convention for stdlib functions like fclose.
This change is necessary to make pugixml successfully compile as part of our game project where we use [vectorcall](https://msdn.microsoft.com/en-us/library/dn375768.aspx) as default calling convention on x64. The function fclose is explicitly marked as cdecl which makes the function incompatible to the function pointer type int(* )(FILE*).
> Do not assume that fclose can be converted to int(*)(FILE*)

- scripts/nuget.autopkg
- scripts/nuget_build.bat
I have attempted to expand the Nuget configuration to include VS 2013 static builds in addition to the VS 2015 that currently exists.
Closes #107
> Expand Nuget Configuration Options

- scripts/nuget.autopkg
This pivot seemed to be causing issues because the NuGet package thought it was actually dynamic.
Refs #107
> Remove static pivot from NuGet autopkg.

- .gitignore
- CMakeLists.txt
- misc/cmake/pugixml.pc
Hi Zeux, 
I have added a basic support for PKG-CONFIG file, which makes life much easier on non-Windows platforms.
Also made minor modfification to create a separate install directory under INCLUDE and LIB directories, I believe those should not break MSVC builds (I'm building on Windows but under MSYS2).
LMK if this works for you.
Best regards,
Peter
> Adding PKG-CONFIG support

- src/pugixml.hpp
- tests/test.hpp
- tests/test_document.cpp
- tests/test_dom_traverse.cpp
- tests/test_write.cpp
- tests/writer_string.hpp
In a member function declaration or definition, 'override' ensures that the function is virtual and is overriding a virtual function from the base class. The program is ill-formed (a compile-time error is generated) if this is not true. Since version 5.1, GCC supports flag '-Wsuggest-override', which warns if 'override' specifier is misssing. We've enabled this flag in our project and found that the specifier is missing in pugixml headers. Although we've disabled the warning for files including pugixml, it might be useful to add 'override' speficiers for headers as we suggest in this pull request.
> Add C++11 'override' specifier

- src/pugixml.cpp
- src/pugixml.hpp
VS 2013 supports C++11, but __cplusplus macro hasn't updated, and its value is still 199711 (C++98?) so the old check always fails, even though the compiler supports C++11. Fun fact is they haven't even updated it in the most recent VS versions that i'm currently using (2015 w/ update 3 and 15 w/ Preview 5)
> Add VS2013 check for C++11 availability

- .travis.yml
- Makefile
- src/pugixml.cpp
- tests/test_compact.cpp
- tests/test_document.cpp
- tests/test_dom_modify.cpp
- tests/test_dom_traverse.cpp
- tests/test_parse.cpp
- tests/test_write.cpp
- tests/test_xpath.cpp
- tests/test_xpath_api.cpp
- tests/test_xpath_functions.cpp
- tests/test_xpath_operators.cpp
- tests/test_xpath_parse.cpp
- tests/test_xpath_paths.cpp
Instead of relying on either exceptions or setjmp during XPath parsing and evaluation, we now do manual error handling & propagate the error to the root of the parse/evaluate call stack, at which point it's converted to a result code or an exception based on PUGIXML_NO_EXCEPTIONS define.
This means we now no longer rely on setjmp in exception-free builds which improves compatibility, and also unifies the error handling between exception/no-exception cases. Additionally, we can switch to no-exception mode in the future (which is likely going to be the case for 2.0 - this breaks compatibility) without causing issues with setjmp which is not always safe to use in the presence of exceptions being thrown (e.g. an allocation function throwing an exception).
Finally, this change re-enables …
> XPath: Remove exceptional control flow

- src/pugixml.cpp
This is accomplished by explicitly marking the fallthrough
using the C++17's `[[fallthrough]]` attribute.
Although `[[fallthrough]]` is C++17, it is supported by
clang++ and g++ >= 7 even if you use, e.g., -std=c++11.
This is a good thing because it allows us to easily silence
these warnings regardless of the used -std flag. (Otherwise
we would have to use `__attribute__((fallthrough))` for g++;
luckily there is no need to do so.)
> Silence g++ 7.0.1 -Wimplicit-fallthrough warnings

- .travis.yml
- src/pugixml.cpp
- tests/main.cpp
- tests/test_document.cpp
This change expands coverage by excluding assert(false) statements from codecov report and by adding tests for loading files with unusual behavior to trigger ftell/fread issues.
> Improve code coverage

- Makefile
- src/pugixml.cpp
- src/pugixml.hpp
- tests/test_document.cpp
This change implements move ctor and assign support for xml_document.
All node handles remain valid after the move and point to the new document; the only exception is the document node itself (that remains unmoved).
Move is O(document size) in theory because it needs to relocate immediate document children (there is just one in conformant documents) and all memory pages; in practice the memory pages only need the header adjusted, which is ~0.1% of the actual data size.
Move requires no allocations in general, except when using compact mode where some moves need to grow the hash table which can fail (throw).
Fixes #104
> Implement move support for xml_document

- tests/test_document.cpp
Apparently at some point OSX behavior when reading /dev/tty switched
from "can't open the file" to "the file can be opened and 0 bytes can be
read from it" which generates a wrong error and doesn't exercise the
code path we care about.
> tests: Fix OSX test failure

- src/pugixml.hpp
MS won't be able to increase __cplusplus soon so as a workaround this pull request adds special treatment of the MSVC compiler. (similar to the support of move semantics)
The override specifier is [supported with compiler 17.0](http://en.cppreference.com/w/cpp/compiler_support) which is part of Visual Studio 2012.
> Enables usage of override specifier for MSVC compilers

- src/pugixml.cpp
- src/pugixml.hpp
Having move special members is only half the deal. If they are not noexcept then for example std::vector::push_back will copy instead of move to keep giving the strong exception guarantee.
Therefore this PR adds noexcept to those special move members that can be made noexcept.
Also see these coding guidelines:
- [Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-move-noexcept)
- [High Integrity C++ Coding Standard](http://www.codingstandard.com/rule/12-5-4-declare-noexcept-the-move-constructor-and-move-assignment-operator/)
> Add noexcept specifiers to move special members where possible

- CMakeLists.txt
- scripts/pugixml.pc.in
There's really never a reason to *not* want this installed. If an option
is needed to specify installing in a versioned subdirectory, this option
should be explicitly described rather than hidden in something else.
As an added bonus, this makes the CMake install code slightly *less*
complicated.
> cmake: always install the pkg-config file

- CMakeLists.txt
- scripts/pugixml.pc.in
- Up to now, the libdir was hardcoded to "lib" inside pugixml.pc and
the install directory of pugixml.pc was "lib/pkgconfig"
- Adds support for lib and lib64 by using CMAKE_INSTALL_LIBDIR variable
> Use CMAKE_INSTALL_LIBDIR for pugixml.pc

- Makefile
- src/pugixml.cpp
- tests/test.cpp
- tests/test_dom_text.cpp
- tests/test_dom_traverse.cpp
- tests/test_xpath.cpp
We had a couple of places in test code and one place in library source
where we used an implicit float->double cast; while it should preserve
the value exactly, gcc/clang implement this warning to make sure uses of
double are intentional.
Fixes #243.
> Fix Wdouble-promotion warnings

- .travis.yml
- Makefile
- tests/test_document.cpp
This commit changes sanitize configuration to fail on the first error
and ignore floating-point division and overflow "errors" that trigger
when we test the corresponding functionality. This makes it possible to
run this on all commits - if new UB or memory safety issues are introduced,
asan/ubsan will catch them.
> Enable config=sanitize in Travis CI

- appveyor.yml
Use cygwin to build coverage build and upload coverage data to codecov.
> Add support for MinGW builds on AppVeyor

- appveyor.yml
We are currently only testing UTF8 mode which means we don't have code
coverage for some UTF->UTF decoding paths.
> Add PUGIXML_WCHAR_MODE configuration to MinGW tests

- .travis.yml
- Makefile
This allows us to reuse this code for MinGW builds.
Additionally disable coverage step for Linux clang - it looks like
Travis has a mismatch in the version of gcov info between clang and gcov
which causes gcov to crash - somehow this crash isn't picked up as a
build error.
> Move unreachable line handling to Makefile

- CMakeLists.txt
- scripts/pugixml.pc.in
Hello,
This commit uses [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) absolute path variables instead of creating such paths manually.
- Use `CMAKE_INSTALL_FULL_LIBDIR` instead of `CMAKE_INSTALL_PREFIX}`/`CMAKE_INSTALL_LIBDIR`
- Use `CMAKE_INSTALL_FULL_INCLUDEDIR` instead of `CMAKE_INSTALL_PREFIX}`/`CMAKE_INSTALL_INCLUDEDIR`
This fixes an installation problem in [Nix](https://nixos.org/nix/) packages, as non-FULL variables are already absolute paths in this case.
> pkg-config: Use CMake GnuInstallDirs FULL vars

- CMakeLists.txt
We need to build static and shared libraries at the same time. This patch worked for us. I set building shared libs off, so its default behaviour is the same as before. The only difference is: If you only want to build shared libs, you have to set BUILD_SHARED_LIBS and unset BUILD_STATIC_LIBS.
> make pugixml build static and shared via cmake

- CMakeLists.txt
We now have a ${LIBRARY} variable that we can either use directly or in
a foreach loop to be able to process either pugixml or pugixml-static
and pugixml-shared targets.
Also fixes incorrect shared library assignment when
BUILD_SHARED_AND_STATIC_LIBS is defined, and only links the static
library in for make check.
> Refactor CMakeLists.txt support for multiple targets

- src/pugixml.cpp
- tests/test_xpath.cpp
- tests/test_xpath_operators.cpp
Given an unsorted sequence, remove_duplicates would sort it using the
pointer value of attributes/nodes and then remove consecutive
duplicates.
This was problematic because it meant that the result of XPath queries
was dependent on the memory allocation pattern. While it's technically
incorrect to rely on the order, this results in easy to miss bugs.
This is particularly common when XPath queries use union operators -
although we also will call remove_duplicates in other cases.
This change reworks the code to use a hash set instead, using the same
hash function we use for compact storage. To make sure it performs well,
we allocate enough buckets for count * 1.5 (assuming all elements are
unique); since each bucket is a single pointer unlike xpath_node which
is two pointers, we need …
> XPath: Make remove_duplicates generate stable order

- contrib/natvis/pugixml_compact.natvis
This PR covers Visual Studio Natvis visualization for PUGIXML_COMPACT build modes.
This is a separate PR since it is harder to get the same display for types containing custom pointer wrappers with run-time decoding.
Additionally, this file requires more upkeep because access to types in anonymous namespaces in not supported by Visual Studio debugger and all member accesses are made through hard-coded offsets.
> Visual Studio Natvis visualization for PUGIXML_COMPACT build mode

- appveyor.yml
- scripts/nuget/pugixml.nuspec
- scripts/nuget_build.ps1
- scripts/pugixml_vs2019.vcxproj
- scripts/pugixml_vs2019_static.vcxproj
- tests/autotest-appveyor.ps1
Create visual studio projects that are vs2019 compliant.
* nuget_build.ps1 : Add two lines to the script that create builds for
v142 build tools
* pugixml_vs2019{,_static}.vcxproj :
Add two visual studio projects that build pugi with the latest SDK and
build tools
> Update nuget creation to VS2019

- CMakeLists.txt
Per @eli-schwartz's recommendations, this PR fixes the pkgconfig file locations. In an attempt to also future-proof it for CMake's config files, we now install them to libdir as well.
> Fix install locations for pkgconfig *and* cmake

- CMakeLists.txt
This fixes the issue discussed just mentioned in #303
> Fix incorrect installation location for exported CMake targets

- src/pugixml.cpp
The current implementation complains if -Wconversions is set in gcc
> explicit casts for -Wconversions warnings in gcc

- CMakeLists.txt
Don't call them pugixml-shared or pugixml-static, because this breaks pkgconfig calls and userspace tools.
> Update CMakeLists.txt to rename the static and shared libraries to pugixml

- src/pugixml.hpp
As mentioned in #91 not using nullptr in C++11 can result in a warning (in my case from clang-tidy). This becomes an issue in the header, as it is included in other cpp files which might have different warning levels than pugixml itself.
> Use nullptr in pugixml.hpp if available, see #91

- CMakeLists.txt
- scripts/pugixml.pc.in
In case of `USE_POSTFIX`, the `POSTFIX` is dependent
on the `CMAKE_BUILD_TYPE`.
Use the correct `POSTFIX` also in the generated **`pugixml.pc`** file.
This results in the following contents of **`pugixml.pc`**:
- Release:
`  Libs: -L${libdir} -lpugixml`
- RelWithDebInfo
`  Libs: -L${libdir} -lpugixml_r`
- MinSizeRel:
`  Libs: -L${libdir} -lpugixml_m`
- Debug:
`  Libs: -L${libdir} -lpugixml_d`
> Fix debug postfix in pkgconfig file

- src/pugixml.cpp
- tests/test_xpath_parse.cpp
Function call arguments are stored in a list which is processed
recursively during optimize(). We now limit the depth of this construct
as well to make sure optimize() doesn't run out of stack space.
Technically optimize() could use a stackless traversal for _next pointer,
but it only seems to meaningfully affect concat and predicate list, so it's
probably better to treat all links as recursive uniformly for now.
> XPath: Fix stack overflow in functions with long argument lists

- src/pugixml.cpp
This is a slightly cleaned up version of #364. Instead of relying on disabling 4996 (which isn't a valid warning code for clang), we now use _wfopen_s and fopen_s when available.
Closes #364.
> Fix MSVC deprecation warnings when using clang-cl

- scripts/pugixml-config.cmake.in
This is not allowed on IMPORTED targets.
---
@randyfan Sorry about that. Thanks for the report. I thought I had tested it, but apparently not.
@zeux 1.11.2 it appears :/ .
> cmake: avoid ALIAS target

- scripts/pugixml-config.cmake.in
target_link_libraries/INTERFACE doesn't seem to work on CMake 3.10, but
directly setting the property does work.
Fixes #390.
> Fix compatibility issue with CMake 3.10

- scripts/pugixml-config.cmake.in
This fixes duplicate target definition errors when find_package(pugixml)
is called twice in a build.
Fixes #393.
> Don't define pugixml import target if it already exists

- src/pugixml.cpp
- src/pugixml.hpp
This prevents usage with C++20 ranges since it does not satisfy
std::weakly_incrementable.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> remove const from xml_node_iterator ++/--

- src/pugixml.hpp
Simple and allows to avoid using std::distance.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> add empty method

- CMakeLists.txt
Added PUGIXML as prefix to all CMake options to avoid naming collisions
with downstream projects.
Removed the cached variable BUILD_DEFINES, since it was unused.
> Add PUGIXML as prefix to CMake options

- tests/test_document.cpp
The _GLIBCXX_HAVE_UNISTD_H relies on pugixml and its tests being built against libstdc++, with LLVM's libc++ this won't be defined. On modern compilers/preprocessors, luckily we can test for includes.
We do so here to include the needed header for unlink, when a) not building for mingw b) we have the __has_include preprocessor facility available and c) the header is in fact available
> Fix include in test_document.cpp when building against libc++

- src/pugixml.cpp
- tests/test_document.cpp
This is the same fix as #497, but we're using auto_deleter instead
because if allocation function throws, we can't rely on an explicit call
to deallocate.
Comes along with two tests that validate the behavior.
> Fix memory leak during OOM in convert_buffer

- src/pugixml.cpp
This change attempts to reduce compact mode overhead during tree access by storing the fields in local variables instead of relying on the compiler to eliminate redundant accesses (which many compilers, notably clang, aren't guaranteed to do).
Fixes #463.
> Optimize compact mode

- src/pugixml.hpp
Support for `nullptr` was added with MS Visual Studio 2010 which has `_MSC_VER == 1600`.
[This Microsoft document](https://docs.microsoft.com/en-us/cpp/porting/visual-cpp-what-s-new-2003-through-2015?view=msvc-170#whats-new-for-c-in-visual-studio-2010) states that `nullptr` support was in fact introduced with 2010, the mapping to `_MSC_VER` was taken from [here](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170).
> Enable usage of nullptr for MSVC 16 and newer (MSVS 2010)

- src/pugixml.cpp
There were two conditions under which xml_document::save_file could previously return true even though the saving failed:
- The last write to the file was buffered in stdio buffer, and it's that last write that would fail due to lack of disk space
- The data has been written correctly but fclose failed to update file metadata, which can result in truncated size / missing inode updates.
This change fixes both by adjusting save_file to fflush before the check, and also checking fclose results. Note that while fflush here is technically redundant, because it's implied by fclose, we must check ferror explicitly anyway, and so it feels a little cleaner to do most of the error handling in save_file_impl, so that the chances of fclose() failing are very slim.
Of course, neither change guarantees …
> Fix error handling in xml_document::save_file

- CMakeLists.txt
This also turns the define for PUGIXML_API into an `$<IF:>`, instead of an
`$<IF:>` with an empty true condition. If this is inadequate, I will
undo it, and place them on separate lines as they were before, but will
most likely use an inverse `$<NOT:>` instead of an `$<IF:>`.
> Fix exported symbols under clang-cl (Closes #503)

- src/pugixml.cpp
- tests/test_document.cpp
- tests/test_dom_traverse.cpp
We use snprintf when stdc is set to C++11, however in C++98 mode we can't use variadic macros, and Xcode 14 complains about the use of sprintf.
It should be safe however to use variadic macros on any remotely recent version of clang on Apple, unless -pedantic is defined which warns against the use of variadic macros in C++98 mode...
This change fixes the problem for the builds that don't specify -pedantic, which is a problem for another day.
> Fix Xcode 14 sprintf deprecation warning

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where pugixml already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
> Add Github CIFuzz action

- Makefile
Fix the make error by adding `firstword()` wrap for environments with pre-settled switches in `$(CXX)`. 
Fixes #556.
> #556 fix makefile err in some env

- src/pugixml.cpp
* https://eel.is/c++draft/lex.name#3.1
"Each identifier that contains a double underscore __ [...] is reserved to the implementation for any use."
@zeux We run `-Wreserved-macro-identifier` on our Clang builds at work, and I'd like to upstream the fix we have been carrying locally. The change here is purely mechanical
sed -i 's|PUGI__|PUGI_DETAIL_|g' src/pugixml.cpp
> Fix `-Wreserved-macro-identifier`

- src/pugixml.cpp
- tests/test_document.cpp
Different OSes have different behavior when trying to fopen/fseek/ftell a folder. On Linux, some systems return 0 size, some systems return an error, and some systems return LONG_MAX. LONG_MAX is particularly problematic because that causes spurious OOMs under address sanitizer.
Using fstat manually cleans this up, however it introduces a new dependency on platform specific headers that we didn't have before, and also has unclear behavior on 64-bit systems wrt 32-bit sizes which will need to be tested further as I'm not certain if the behavior needs to be special-cased only for MSVC/MinGW, which are currently not handled by this path (unless MinGW defines __unix__...)
Fixes #560.
> Fix get_file_size behavior inconsistency for folders

- src/pugixml.cpp
- src/pugixml.hpp
Using Apple clang (clang-1400.0.29.202) with `-Wweak-vtables` would produce the following warning:
> 'xml_writer' has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit [-Wweak-vtables]
Using the "defaulted default constructor" prevents this.
> Fix weak vtable warning regarding xml_writer

- CMakeLists.txt
Implementation of PUGIXML_STATIC_CRT for newer CMake versions (3.15+) depend on MSVC_RUNTIME_LIBRARY, but this only works if the policy is defined *before* the project.
Fixes #544.
> build: Fix CMake PUGIXML_STATIC_CRT behavior

- src/pugixml.cpp
Hi, cannot compile pugixml for old GCC (versions 2.95.3 and 3.3.5). It happened when I try to cross-compile my project for QNX 6.3.2. There is a bug with header files. It can be fixed by reordering (put `<stdlib.h>` above all other headers) or by checking the compiler version. Errors:
```cpp
libs/pugixml/src/pugixml.cpp: In
function `void* pugi::impl::<unnamed>::default_allocate(unsigned int)':
libs/pugixml/src/pugixml.cpp:195: error: `
malloc' undeclared (first use this function)
libs/pugixml/src/pugixml.cpp:195: error: (Each
undeclared identifier is reported only once for each function it appears 
in.)
libs/pugixml/src/pugixml.cpp: In
function `void pugi::impl::<unnamed>::default_deallocate(void*)':
libs/pugixml/src/pugixml.cpp:200: error: `
free' undeclared (first use this function) …
```
> Fix compilation errors on old GCC (2.95.3, 3.3.5)

- CMakeLists.txt
With CMake 3.27, we get a deprecation warning:
> Compatibility with CMake &lt; 3.5 will be removed from a future version of CMake. Update the VERSION argument &lt;min&gt; value or use a ...&lt;max&gt; suffix to tell CMake that the project does not need compatibility with older versions.
Bump min version to 3.5 to remove warning.
> {cmake} Fix deprecation warning by updating min version to 3.5

- docs/manual.adoc
- src/pugixml.cpp
- src/pugixml.hpp
- tests/test_dom_modify.cpp
* bool xml_attribute::set_name(const char_t* rhs, size_t sz)
* xml_attribute xml_node::append_attribute(const char_t* name_, size_t sz)
* xml_node xml_node::append_child(const char_t* name_, size_t sz)
* xml_attribute xml_node::attribute(const char_t* name_, size_t sz) const
* xml_node xml_node::child(const char_t* name_, size_t sz) const
* bool xml_node::set_name(const char_t* rhs, size_t sz)
> Add overloads with size_t type argument

- CMakeLists.txt
Currently, the CMakeLists.txt unconditionally includes CTest. As a consequence, BUILD_TESTING is defined by CTest, which has unintended consequences for any project that uses pugixml: a project that has a certain configuration in which the tests are disabled suddenly finds that testing is enabled after including pugixml.
By making include(CTest) conditional on PUGIXML_BUILD_TESTS, BUILD_TESTING is not set anymore in other projects.
> build: only include CTest when building the pugixml tests

- CMakeLists.txt
When pugixml is used as a submodule, installation rules are not required.
Additionally, it may cause issues when pugixml is installed / exported by parent project:
```
CMake Error: install(EXPORT "OpenVINODeveloperTargets" ...) includes target "inference_engine_s" which requires target "pugixml-static" that is not in this export set, but in multiple other export sets: runtime/cmake/OpenVINOTargets.cmake, lib/cmake/pugixml/pugixml-targets.cmake.
An exported target cannot depend upon another target which is exported multiple times. Consider consolidating the exports of the "pugixml-static" target to a single export.
CMake Error: install(EXPORT "OpenVINODeveloperTargets" ...) includes target "func_test_utils" which requires target "pugixml-static" that is not in this export set, but in …
```
> Added cmake option to disable install rules

- src/pugixml.cpp
Fixed a GCC warning about using a const literal zero in place of nullptr (-Wzero-as-null-pointer-constant) by using the already defined PUGIXML_NULL macro when the C++ version supports nullptr.
> Replaced 0 with PUGIXML_NULL when a nullptr would have been needed.

- tests/fuzz_xpath.cpp
This change increases code coverage significantly during fuzzing as it excersizes the query code against an arbitrary file.  I've also updated the fuzzer to use LLVM's FuzzedDataProvider which makes the fuzzer a little easier to understand/reason about.
> fuzzer: excersizes query code on xml doc

- Makefile
We used to need to silence float-divide-by-zero and float-cast-overflow sanitizers since clang used a finite valid floating point value range. Fortunately, since clang-9 UBSAN properly handles various primitive operations per IEEE-754 so we no longer need this workaround.
Also use fork=16 mode for fuzz targets to make it easier to run fuzzing locally.
> Update config=sanitize and fuzz targets

- src/pugixml.cpp
@zeux We build with `-Wuseless-cast` internally, and it would be great to get this upstreamed.
> Fix `-Wuseless-cast`

- appveyor.yml
- tests/autotest-appveyor.ps1
- Use /MP for cl.exe builds to try to take advantage of 2 cores
- Use -j2 for MinGW builds to do the same
- Don't build AppVeyor on non-master branches to avoid double builds for PRs from this repository
MP and j2 aren't as impactful as I'd like them to be but they do result in ~25% build time reduction. The branch restriction should additionally cut the time for internal PRs 2x.
> AppVeyor build optimizations

- src/pugixml.cpp
- src/pugixml.hpp
The explicit specification of default template arguments is repetitive and dates back to the versions of pugixml that tried to forward-declare all STL classes manually, which ran into issues with default arguments in some STL versions.
We've since abandoned this idea and use string/iosfwd includes, as such it should be fine to rely on default arguments.
Note: while we could use std::wstring, this had compatibility issues with some very early versions of Android SDK. Out of abundance of caution, we keep basic_i/ostream and basic_string in tact. We could use std::string but we might need to replace these in char8 mode if that ever gets merged.
> Use cleaner references to STL classes

- src/pugixml.cpp
stat.h defines struct stat to use long long on Android NDK when targeting x86; off_t however is defined as long, which is 32-bit (unlike other Unix-like platforms). This results in a narrowing conversion which produces a warning, and can also result in silently reading a prefix of a huge file instead of a clean "out of memory" error. To avoid this, we need to deduce the type of stat::st_size which requires moving the length conversion logic to a templated function since we can't use `auto`/`decltype` before C++11.
Fixes #603.
> Fix -Wshorten-64-to-32 warning on Android NDK when targeting x86

- src/pugixml.cpp
Normally, as_utf8_begin et al are used in STL functions but when STL is disabled, these are only used if the target platform lacks first class support for wchar_t FILE* APIs. With some warning levels we consequently can get warnings about these functions not being referenced; this affects MSVC (when using aggressive /Wall warning setup) and MinGW (when using -Wall which should work on gcc without warnings, hence the fix).
Not defining these in the first place is difficult because of the complexity of the selection logic for open_file_wide so for now just mark these as unused. The strange (void)& syntax is needed for MSVC to not trigger another warning...
The workaround is narrowly scoped to avoid unforeseen compatibility issues.
Fixes #619.
> Work around 'unreferenced function' warnings in NO_STL builds

- src/pugixml.cpp
This is a preemptive patch, for something that is currently not a bug, but could become one in the future.
`xml_document::save` currently constructs `buffered_writer` with parameter `encoding`:
https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L7459
The `xml_buffered_writer` constructor then invokes `get_write_encoding` to interpret that `user_encoding`:
https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L3753
`get_write_encoding` can modify the value of `encoding` (that is subsequently used to initialize `buffered_writer.encoding`)
https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L3618
`xml_document::save` proceeds to perform two checks on the unmodified local function parameter `encoding`:
https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L7463 …
> xmldocument::save: use encoding interpreted by get_write_encoding in buffered_writer constructor

- docs/manual.adoc
- src/pugixml.cpp
- src/pugixml.hpp
`throw()` was deprecated in C++11 and removed in C++17. `noexcept` is the appropriate fix.
> throw() -> noexcept

- CMakeLists.txt
Even if the compiler supports C++17, we define CMAKE_CXX_STANDARD as 11 by default which implicitly disables string_view support; for now warn in this case.
Note: I am not sure *why* we set CMAKE_CXX_STANDARD to 11. This has been added 5 years ago as part of CMake modernization but I don't know what the justification was for this particular change. We could set it to 17 if the option is enabled, but since the intent for the STRING_VIEW option to be there just for transition, after this option is removed and string_view is enabled by default, C++17 will still need to be set by the user.
We could also set CMAKE_CXX_STANDARD to 17  by default (and remove CMAKE_CXX_STANDARD_REQUIRED to avoid compatibility issues); I'm not sure what the implications for a change like this would be but that's …
> Warn if PUGIXML_STRING_VIEW is set without CMAKE_CXX_STANDARD

- .github/workflows/build.yml
- appveyor.yml
- tests/cmake-appveyor.ps1
We now test CMake for Linux/macOS on GHA, and test it for all supported VS versions on AppVeyor (previously CMake was only exercised in GHA on Windows).
To reduce the impact on AppVeyor build time we only run a quick library build without actually compiling or running tests. This can be expanded in the future if need be.
> Enhance CMake testing in CI

- .github/workflows/build.yml
- CMakeLists.txt
- docs/manual.adoc
- docs/manual.html
- scripts/pugixml_vs2019.vcxproj
- scripts/pugixml_vs2019_static.vcxproj
- scripts/pugixml_vs2022.vcxproj
- scripts/pugixml_vs2022_static.vcxproj
- src/pugiconfig.hpp
- src/pugixml.hpp
- tests/autotest-appveyor.ps1
This PR enables std::string_view by default when the compiler supports C++17, and also tries to enable C++17 in a few cases when the compiler should support it. Notably, vcxproj files for VS2019/2022 now enable /std:c++17, and CMake enables C++17 when no specific version is set via CMAKE_CXX_STANDARD; we are now using CMAKE_CXX_STANDARD_REQUIRED=OFF to use CMake's transparent C++ version downgrade.
I originally expected that the next release should go out with string_view being opt-in. However, I'm thinking it might be better to just go all-in:
1. The release doesn't really have much else outside of a few compatibility fixes. Even if there is a compatibility regression, the only way to find out is to try, and if the release has issues this wouldn't block any other features.
2. During …
> Auto-detect std::string_view support by default

- scripts/sbom.cdx.json
Hi,
My name is Richard Hughes and I'm a developer at Red Hat. I'm the maintainer of fwupd and LVFS, and am trying to improve software supply chain security by encouraging OEMs, ODMs and IBVs to ship Software Bill of Materials with each firmware binary blob (SBOMs).
I'm working alongside lots of other companies proactively trying to do the right thing. The reason I've opened this pull request is because your project is either used in the *build process* of a firmware we care about (e.g. EDK II, or coreboot) or is built *into the firmware binary* itself. Although my personal focus is on firmware, the SBOM file is in CycloneDX format (one of the most popular industry standards) which makes it also useful when building containers or OS images too.
I would like to contribute this template SBOM …
> Add a SBOM template in CycloneDX format

- docs/manual.adoc
- docs/manual.html
Found via `codespell -q 3 -D ../dictionary.txt -L parametere,thirdparty`
> docs: fix typo

- src/pugixml.cpp
- tests/test_document.cpp
Previously, calling xml_document::load_string on an empty buffer resulted in a single byte allocation for the buffer copy; this allocation was redundant as no data was parsed, so we now add the same early-out that already exists in xml_parser::parse to load_buffer_impl.
This should almost never matter but might help applications that for some strange reason frequently parse empty documents without a higher level size check on the app side.
> Early out in load_buffer for empty inputs to avoid allocations
